gui:
  sidePanelWidth: 0.3
  timeFormat: 2006-01-02 15:04 +09
  shortTimeFormat: 03:04PM
  nerdFontsVersion: 3
  filterMode: fuzzy
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
