[tools]
usage = "latest"
node = "latest"
deno = "latest"
bun = "latest"
uv = "latest"
"npm:npm-check-updates" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"aqua:aws-cli" = "latest"
"aqua:aws-sam-cli" = "latest"

[env]
_.path = ["{{cwd}}/node_modules/.bin", "{{config_root}}/node_modules/.bin"]

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
python.uv_venv_auto = true
